eval "$(starship init bash)"
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORM=wayland
export PATH="$HOME/.config/emacs/bin:$PATH" 
export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"
export DOOMDIR="$HOME/.dotfiles/nixos/dots/doom"
export GEM_HOME="$HOME/.gem"
export GEM_PATH="$HOME/.gem"
export PATH="$HOME/.gem/bin:$PATH"




 alias nixos-rebuild-tars='sudo nixos-rebuild switch --flake ~/.dotfiles/nixos/ #tars'
 alias devshell="nix develop ~/.dotfiles/nixos#"
 alias mtdoom="doom run &"
 alias mount_gdrive='rclone mount --daemon gdrive:Obsidian /home/viku/Documents/gdrive'

 alias unmount_gdrive='fusermount -uz /home/viku/Documents/gdrive'

 alias vaults="cd /home/viku/Documents/gdrive/MyVault"
 alias sites="cd /home/viku/Documents/sites"


