{
  imports = [
    ./airline.nix
    ./alpha.nix
    ./comment.nix
    ./cmp.nix
    ./floaterm.nix
    ./harpoon.nix
    ./image.nix
    ./lsp.nix
    ./mini.nix
    ./neotree.nix
    ./nixplugin.nix
    ./notify.nix
    ./telescope.nix
    ./tmux-navigator.nix
    ./todo-comments.nix
    ./transparent.nix
    ./treesitter.nix
    #./obsidian.nix
  ];
}
